### ISSUE TITLE
Missing airco mode selector Heater/Cooler

### ISSUE THREAD

**Issue by rpkbs** [aivus/com.gree#130]
Hi,
I just installed some Tosot airco units, but in the Homey app I cannot select the heater function.
Can this function be added to the gree app?

Kind regards
Robin

**Comment by aivus** [comment]
@rpkbs please use [test channel to install 0.8.0 version](https://homey.app/de-de/app/com.gree/Gree/test/).
There you should have "HVAC Mode" capability to configure.

**Comment by rpkbs** [comment]
Hi, thanks.

Is there also a horizontal swing available?

Thanks for your effort.



________________________________

**Comment by aivus** [comment]
> Is there also a horizontal swing available?

Yes, in test version

**Comment by rpkbs** [comment]
Thanks for the quick reply.

Found it.

Greetings


________________________________
