### ISSUE TITLE
Enabling the minimum temperature to +8 degrees

### ISSUE THREAD

**Issue by Tuokki1** [aivus/com.gree#166]
A maintenance temperature of **+8 degrees** is important especially when the heat pump is used, for example, to heat the summer cottage in the winter at times when you are not there.

Br,

Tuomas

**Comment by aivus** [comment]
Hello Tuomas,

Are you talking about special mode "+8 degree", right? And Not about setting temperature manually to +8?

**Comment by aivus** [comment]
@Tuokki1 I've added support of "8°C heating" mode to the latest test version (0.9.4).
You can find this mode near the "turbo mode"
