### ISSUE TITLE
No new devices have been found

### ISSUE THREAD

**Issue by zawinull** [aivus/com.gree#21]
Doesn't work with Gree GWH12QC HVAC: "No new devices have been found."

**Comment by aivus** [comment]
Hi @zawinull 

Did you connect your HVAC using vendor's app to the same WiFi network where Homey is?

**Comment by zawinull** [comment]
Yes, my HVAC is using Gree's (Gree+) app and connected to the same wifi network where Homey is. Btw, Gree+ is a really crappy app, connecting to Gree's cloud servers often takes 1-3 minutes, producing network delay errors: https://play.google.com/store/apps/details?id=com.gree.greeplus&hl=en&showAllReviews=true

**Comment by aivus** [comment]
I used https://play.google.com/store/apps/details?id=com.gree.ewpesmart and it seems that it's almost the same app you've mentioned.

Could you please try to reconnect your HVAC to the WiFi network following next instructions:

1. Make sure your HVAC is running in AP mode. You can reset the WiFi config by pressing MODE +WIFI (or MODE + TURBO) on the AC remote for 5s.
2. Connect HVAC using vendor's app or CLI like mentioned [here](https://github.com/aivus/com.gree/wiki/Frequently-Asked-Questions) (if you know how to do it)

**Comment by zawinull** [comment]
I reconnected the HVAC but no success.  According to my observation Gree hvacs need more than 30 seconds to process and return a response, because of this try to set response timeout value as high as possible.

**Comment by aivus** [comment]
App continuously scan network to find any devices.
If HVAC doesn't displayed in the app it means that app didn't get response from the HVAC.

I'm adding additional logging to the app right now and will contact your additionally to debug this  deeper.

If you will found a way to add your HVAC to the app before - give me know about it.

**Comment by aivus** [comment]
@zawinull 

Could you please share your email address which you are using in homey?
I will push test version for you via Homey Apps with additional logging.

Thanks.

**Comment by aivus** [comment]
My email: ilya@antipenko.pp.ua

**Comment by aivus** [comment]
Resolved in PM.

Reason of this was a "client isolation"/"AP Isolation" mode of the router which prevents direct interaction between WiFi clients.

After disabling it - app works.

@zawinull please switch to stable version of the app as `alpha` will be used for investigating other issues.
