### ISSUE TITLE
Enable support of Google Home

### ISSUE THREAD

**Issue by aivus** [aivus/com.gree#46]
It was reported in #41 that Google Home doesn't allow to change modes.

And proposed the fix with renaming `hvac_mode` capability to `thermostat_mode`
https://github.com/aivus/com.gree/pull/41/commits/4214a6ebd126c03c394cd46167f87dec0d685e3e.

Need to verify this solution

**Comment by denniedegroot** [comment]
It also enables some color schemes in the Homey app when cooling/heating.

**Comment by aivus** [comment]
@denniedegroot I'm going to release this changes soon.

But it provides limited support as it's impossible to turn AC off using Google Home app.

Google Home uses thermostat mode for turning off as well as for selecting modes, but app has separate on/off capabilities for this.
