### ISSUE TITLE
Innova works with Gree app

### ISSUE THREAD

**Issue by Melkutt** [aivus/com.gree#72]
I have a INNOVA TITANIUM 12 and it's seams to work grate with your app

Regards Melker

**Comment by aivus** [comment]
Thanks for letting me know.
I'll add it to the list of supported devices

**Comment by boeselhack** [comment]
Hi Aivus,

I have an Innova 2.0 HP 10 and 12 (not the ELEC versions) and I’m stuck with the error
“Device Unavailable – Your HVAC went offline. Trying to reconnect…”The dedicated “Innova 2.0 AC” app does not work (local API returns Connection refused on port 80).  
The official Innova app works fine (cloud only).  
The Gree app finds the device, but it never comes online.

Diagnostics report:
0027f0f1-72ce-495c-86c8-97c49f9b10f5
Firmware version shown in device settings: 54

Any help would be greatly appreciated.
Thanks!
Markus
