### ISSUE TITLE
Gree GWH12ACC not found

### ISSUE THREAD

**Issue by rentisob** [aivus/com.gree#80]
Hi Aivus,

I have 2 Gree air conditioners (types: GWH18ACDXF and GWH12ACC) one of them is working great (GWH18ACDXF) with your app in Homey, but the second one (GWH12ACC) annot be integrated to Homey, the app says: No new devices have been found.
Both systems are using the same Wifi SSID, and integrated into the Ewpe Smart application.
Do you know what can be the reason? Thanks for your help!

**Comment by aivus** [comment]
Hey @rentisob 👋 

Technically app sends a broadcast message to the network and AC should answer on it to be displayed on the pairing page.

It would be nice to check that you don't have any kind of "Client isolation" enabled on your router for Wi-Fi clients.

Also, could you please do next:
* open the pairing page and wait for 60 seconds.
* Go back to the list of Homey devices, then go to the "More" -> "Apps" -> "Gree" -> "Gear" symbol -> "Create Diagnostic report". Inside the message mention your nickname.

I'll check does Homey receive any responses or no.

**Comment by rentisob** [comment]
Hey Aivus,
Tested it today, waited 60 seconds and it appeared on the list, so it's working fine now.
Thank you for your support!

**Comment by aivus** [comment]
Nice to hear it
