### ISSUE TITLE
Some devices cannot connect to the app

### ISSUE THREAD

**Issue by aivus** [aivus/com.gree#85]
Could be caused by using different encryption key in new firmwares.
See https://github.com/tomikaa87/gree-remote/issues/36

logs:
```
>>> cid:502cc6b01e79: 11/24/2022, 12:47:02 PM
SOCKET.SEND { t: 'scan' }
>>> cid:502cc6b01e79: 11/24/2022, 12:47:02 PM
IN.MSG {
  t: 'pack',
  i: 1,
  uid: 0,
  cid: '502cc6b01e79',
  tcid: 'app',
  pack: 'LP24Ek0OaYogxs3iQLjL4PD+1uB4aq/dGgEbn8pR7V1YT1PXPBDouOPiWHaG4G8lz22fUZtUbkblUYF5BzlKDV9xeQzMlsaP4RKBtrnsDrMmwHkrcyvRywIl52ZuUW8EzlDvl347hXSddiQKR6Iweu80HbfgK3MNVtBb+mRtQFyio7f3xDWMYEIeftEUXGX8V+aYzyhrw8Yt6UvgVWxkZdHmnfSQ8JdBj+nhexr6JgstnoBYFa+c0wD5j9MjNjAT'
}
>>> cid:502cc6b01e79: 11/24/2022, 12:47:02 PM
IN.MSG.UNPACK {
  t: 'dev',
  cid: '502cc6b01e79',
  bc: 'gree',
  brand: 'gree',
  catalog: 'gree',
  mac: '502cc6b01e79',
  mid: '9300',
  model: 'gree',
  name: '',
  series: 'gree',
  vender: '1',
  ver: 'V5.0.0.0',
  lock: 0
}
>>> cid:502cc6b01e79: 11/24/2022, 12:47:02 PM
SOCKET.SEND {
  cid: 'app',
  i: 1,
  t: 'pack',
  uid: 0,
  pack: 'DYtM4OpY0Xlx+jChSGr01CUUCFjuF79CQPESynbXOcqj9mrs/0p7GUTdWxmNaBUt'
}
>>> cid:502cc6b01e79: 11/24/2022, 12:47:05 PM
SOCKET Unable to connect. Retrying...
```

**Comment by aivus** [comment]
Additional references:
* https://github.com/tomikaa87/gree-remote/issues/52
* https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/pull/165

**Comment by patrykwozinski** [comment]
Hey, I have exactly the same issue. Today I've installed 2 Gree Amber Prestige ACs, both connected to my 2.4G network. They are searchable via Gree app, but in Homey I see only info about "Your HVAC went Offline". Of course, I have the latest firmware - so it sounds like this problem with encryption.

**Comment by dsaw703** [comment]
Confirmed for me as well with 1.21 firmware. 

Is there anything I could do to assist,

**Comment by aivus** [comment]
Hello there,

I just released test version with the possible fix, please [follow this steps](https://community.homey.app/t/app-pro-gree-hvac-app/30801/153?u=aivus)

**Comment by dsaw703** [comment]
Hi, this fix works with the AC units using firmware V1.23, but does not work with wired controllers ("Main" as denoted in Gree App) using firmware V1.40.

**Comment by aivus** [comment]
@dsaw703 I'm not aware of wired controllers and don't really know what is the difference in communication in that case.

**Comment by dsaw703** [comment]
Did you see the log that I had sent where I had deleted all of my units, except for the ones controlled by the wired units?  The wired units are visible and can be controlled in the gree app.  They show up in Homey, just can't be controlled as they show as offline.

Is there any other info I can get you?

Thanks.
________________________________

**Comment by aivus** [comment]
@dsaw703 do you have a diagnostic report id? So I can find your report across others?

**Comment by dsaw703** [comment]
Here are the details. This was ran a month ago, or so.

8ae012c5-e25e-4316-abdb-10117c468f0c

I removed all units that were working from the system to isolate the 2 that were not. I entered debug mode, using V2 with the latest version 0.9.4.

I then turned each unit on with the Gree app, adjusted the temperature, then turned each unit off.

Thanks.

Doug
________________________________

**Comment by aivus** [comment]
Found it.

Is it the same on the latest versions (0.9.9/0.9.10)?

**Comment by dsaw703** [comment]
No, this was done on 0.9.4.  Still doesnt work on latest.

Did you want me to repeat the process on the current version?


Doug
________________________________

**Comment by aivus** [comment]
We've improved support of the new firmwares. Please check https://homey.app/de-de/app/com.gree/Gree/test/
